services:
    app.user_repository:
        class: App\Repository\UserRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - App\Entity\User

    app.article_repository:
        class: App\Repository\ArticleRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - App\Entity\Article

    app.production_queue_repository:
        class: App\Repository\ProductionQueueRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - App\Entity\ProductionQueue

    app.purchase_repositories:
        class: App\Repository\PurchaseRepositories
        arguments:
            - '@app.article_repository'
            - '@app.user_repository'
