app_ping:
    path: /ping
    controller: App\Controller\DefaultController::ping

app_shop_purchase:
    path: /shop/purchase/{userId}/{articleId}
    controller: App\Controller\ShopController::purchase
